"""Inno Setup 安装包构建 -> versions/vX.Y.Z/dist/ProjectDock_Setup_vX.Y.Z.exe。

流程：PyInstaller 构建 windowed release（onedir）→ 生成 .iss 脚本 → ISCC 编译安装包。
安装包默认安装到 %LOCALAPPDATA%/Programs/ProjectDock（无需管理员），
自动关闭正在运行的应用（CloseApplications=force），安装后可选立即运行。
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from build_utils import current_version, prepare_dist, archive_old_exes

ROOT = Path(__file__).resolve().parent
WEB = ROOT / "web"
ENTRY = ROOT / "run.py"

# Inno Setup 安装位置（winget 默认装到用户目录）
ISCC_CANDIDATES = [
    Path.home() / "AppData" / "Local" / "Programs" / "Inno Setup 6" / "ISCC.exe",
    Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
    Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
]

APP_GUID = "B6A9F1E2-9C4D-4A7E-8F3B-1A2B3C4D5E6F"


def find_iscc() -> Path | None:
    for c in ISCC_CANDIDATES:
        if c.is_file():
            return c
    return None


def write_iss(iss_path: Path, out: Path, app_dir: Path, version: str) -> None:
    exe_name = f"ProjectDock_v{version}.exe"
    template = r"""; ProjectDock Setup script (generated by build_setup.py)
#define MyAppName "ProjectDock"
#define MyAppVersion "@@VERSION@@"
#define MyAppExeName "@@EXE@@"

[Setup]
AppId=@@GUID@@
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=ProjectDock
DefaultDirName={localappdata}\Programs\ProjectDock
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=@@OUT@@
OutputBaseFilename=ProjectDock_Setup_v@@VERSION@@
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
CloseApplications=force
RestartApplications=no
UninstallDisplayIcon={app}\{#MyAppExeName}

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional tasks:"; Flags: unchecked

[Files]
Source: "@@APPDIR@@\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall
"""
    text = (template
            .replace("@@GUID@@", APP_GUID)
            .replace("@@VERSION@@", version)
            .replace("@@EXE@@", exe_name)
            .replace("@@OUT@@", str(out))
            .replace("@@APPDIR@@", str(app_dir)))
    # Inno Setup 6 需要 UTF-8 BOM 才能正确解析含中文路径的脚本
    iss_path.write_text(text, encoding="utf-8-sig")


def main() -> None:
    iscc = find_iscc()
    if not iscc:
        sys.exit("未找到 Inno Setup（ISCC.exe）。请先安装：winget install JRSoftware.InnoSetup")
    version = current_version()
    archive_old_exes()
    out = prepare_dist()
    app_dir = out / f"ProjectDock_v{version}"

    print(f"[build_setup] 1/3 构建 windowed release v{version}")
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--windowed",
        "--name", f"ProjectDock_v{version}",
        "--distpath", str(out),
        "--workpath", str(ROOT / "build" / "release"),
        "--specpath", str(ROOT / "build"),
        "--add-data", f"{WEB};web",
        "--paths", str(ROOT / "src"),
        "--collect-all", "uvicorn",
        "--collect-all", "fastapi",
        "--hidden-import", "pydantic",
        str(ENTRY),
    ]
    subprocess.check_call(cmd)

    print(f"[build_setup] 2/3 生成安装脚本 {app_dir.name}")
    iss_path = ROOT / "build" / f"ProjectDock_v{version}.iss"
    write_iss(iss_path, out, app_dir, version)

    print("[build_setup] 3/3 编译安装包（ISCC）")
    subprocess.check_call([str(iscc), "/Qp", str(iss_path)])
    setup = out / f"ProjectDock_Setup_v{version}.exe"
    if not setup.is_file():
        sys.exit("安装包编译失败：未生成输出文件")
    print(f"[build_setup] 完成 -> {setup}（{setup.stat().st_size / 1048576:.1f} MB）")


if __name__ == "__main__":
    main()
